name: bookia
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  gap: ^3.0.1
  pinput: ^5.0.0
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  meta: ^1.15.0
  bloc: ^8.1.4
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  pretty_dio_logger: ^1.4.0
  intl: ^0.20.1
  image_picker: ^1.1.2
  maps_launcher: ^2.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/whatsapp.png

  # fonts:
  fonts:
    - family: DM Serif Display
      fonts:
        - asset: assets/fonts/DMSerifDisplay-Regular.ttf
